---
- name: Pull Docker Image of Calculator
  hosts: all

  tasks:
    - name: Pull Image
      shell: docker pull anshavikhanna/calculator:latest

    - name: Run the container
      shell: docker create -it --name Calculator anshavikhanna/calculator